version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        PYTHON_VERSION: ${PYTHON_VERSION}
    container_name: backend
    restart: unless-stopped
    networks:
      - app

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
      args:
        NGINX_VERSION: ${NGINX_VERSION}
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app

networks:
  app:
    driver: bridge