version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: unless-stopped
    ports:
      - "${APP_PORT}:8080"
    networks:
      - app

  nginx:
    image: nginx:${NGINX_VERSION}
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    user: "root"   # нужно для VirtualBox
    depends_on:
      - backend
    networks:
      - app

networks:
  app:
    driver: bridge