server {
	listen 80 default_server;
	listen [::]:80 default_server;

	root /media/sf_Shared/StackBridge-Technical-Task/frontend;

	access_log /var/log/nginx/access.log main;

	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;

		proxy_pass http://backend_servers;
}

server {
	listen 443 ssl;
	server_name _;
	
	ssl_certificate /etc/nginx/ssl/server.crt;
	ssl_certificate_key /etc/nginx/ssl/server.key;

	location / {
		proxy_pass http://backend_servers;
	}
}
